version: "3"
services:
  app:
    build:
      context: "docker/app/"
    ports:
      - 8000:80
    volumes:
      - "./public/:/var/www/html"
      - "./docker/app/:/etc/httpd/conf/httpd.conf" # httpd.conf を自由にいじれるように
    depends_on:
      - mysql
  mysql:
    build:
      context: "docker/mysql/"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - "storage:/var/lib/mysql"
      - "./docker/mysql/initdb/:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=pass
    depends_on:
      - mysql
volumes:
  storage: